
version: '3'

services:
  bot:
    build:
      context: .
    restart: on-failure
    ports:
      - 8443:8443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    env_file:
      ./.env/db.env
    environment:
     - PGDATA=/var/lib/postgresql/data/clozapinum